Qemu external snap test
canonical/lxd-ci pull request #243
Opened 2024-07-15 16:02 UTC by mihalicyn

2024-07-15 16:58 UTC, simondeziel commented on tests/qemu-external-vm
> +git clone "https://github.com/canonical/lxd-pkg-snap.git" -b "latest-edge"
```suggestion
git clone --depth=1 "https://github.com/canonical/lxd-pkg-snap.git" -b "latest-edge"
```
Will be a tad faster ;)

2024-07-15 16:58 UTC, simondeziel commented on tests/qemu-external-vm
> +cat /proc/${serverPID}/environ | grep LIBGL_DRIVERS
```suggestion
grep -awF LIBGL_DRIVERS /proc/${serverPID}/environ
```

2024-07-16 07:19 UTC, tomponline commented
Looks like some shellcheck issues.

2024-07-16 08:32 UTC, mihalicyn commented on tests/qemu-external-vm
> +git clone "https://github.com/canonical/lxd-pkg-snap.git" -b "latest-edge"
Fixed! Thanks!

2024-07-16 08:32 UTC, mihalicyn commented on tests/qemu-external-vm
> +cat /proc/${serverPID}/environ | grep LIBGL_DRIVERS
Fixed! Thanks!

2024-07-16 11:43 UTC, mihalicyn commented
Run gh extension install actions/gh-actions-cache
  gh extension install actions/gh-actions-cache
  gh actions-cache delete "cache-20240716" --confirm
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PURGE_LXD: 1
    GH_TOKEN: ***
Error: Resource not accessible by integration

2024-07-16 12:53 UTC, mihalicyn commented
It works in the fork repo. So, no problems with cache anymore, hopefully.

2024-07-16 12:55 UTC, tomponline requested changes
Please can you address or silence the shellcheck issues.

2024-07-16 12:56 UTC, mihalicyn commented
> Please can you address or silence the shellcheck issues.

all of them are obsolete

2024-07-16 12:56 UTC, tomponline commented on tests/qemu-external-vm
> +snap install "${SNAP_TO_INSTALL_PATH}" --devmode # TODO: change to --dangerous
Please address this TODO :)

2024-07-16 12:58 UTC, tomponline commented on tests/qemu-external-vm
> +snap install "${SNAP_TO_INSTALL_PATH}" --devmode # TODO: change to --dangerous
ah ok thanks!

2024-07-16 13:01 UTC, mihalicyn commented on tests/qemu-external-vm
> +snap install "${SNAP_TO_INSTALL_PATH}" --devmode # TODO: change to --dangerous
Have fixed! Thanks!

2024-07-16 13:42 UTC, tomponline approved these changes

2024-07-16 13:43 UTC, tomponline commented
Thanks!

2024-07-16 13:43 UTC, merged