Adapt some tests scripts from lxc-ci to Openstack
canonical/lxd-ci pull request #4
Opened 2023-07-20 17:33 UTC by simondeziel

From the `main.sh` test list, `cgroup1` is failing on `jammy`. Previously in `lxc-ci` we used to test `cgroup2` along with `jammy` but I think that's already `jammy`'s default which is why I switched to `cgroup1`:

```
./bin/openstack-run jammy cgroup1 tests/cgroup
```

However, the following works:

```
./bin/openstack-run focal default tests/cgroup
```

So it seems like a regression to me.

2023-07-20 18:05 UTC, tomponline requested changes
Looks like this duplicates some of the tests I cleaned up (partially} today and pushed in as part of the lxd 5.16 manual test run. Please can you update it so there's n9 duplication. Thanks

2023-07-20 18:13 UTC, tomponline commented on cloud-init.user-data.yaml
> +  # no need for backports/security nor restricted/multiverse
Could you explain why in the comments as well as what.

2023-07-20 18:19 UTC, tomponline reviewed
Looking good! Thanks

2023-07-21 10:46 UTC, simondeziel commented
I couldn't find the duplicated manual tests you referred to, would you mind pointing them out, please?

2023-07-21 13:52 UTC, tomponline commented
> 

https://github.com/canonical/lxd-ci/blob/main/tests/test-lxd-network-bridge-firewall
https://github.com/canonical/lxd-ci/blob/main/tests/test-lxd-network-ovn
https://github.com/canonical/lxd-ci/blob/main/tests/test-lxd-storage-buckets

I missed interception actually so would be good to bring that one across.

2023-08-01 13:47 UTC, tomponline approved these changes

2023-08-01 13:47 UTC, merged