tests/cpu-vm: reject `limits.kernel.*` for VMs
canonical/lxd-ci pull request #98
Opened 2024-03-06 22:50 UTC by MggMuggins

...and allow them in profiles. I chose not to go with @simondeziel's suggestion to use `--empty` as the tests fit well enough in `cpu-vm`, but I'm happy to spin up a new test if needed.

Resolves https://github.com/canonical/lxd/pull/13051

2024-03-06 23:02 UTC, simondeziel commented
@MggMuggins reusing an existing VM is indeed better than creating a new one, even empty. That said, the test currently passes for the wrong reason:

```
+ lxc config set v1 limits.kernel.as=1GiB
Error: Key "limits.kernel.as" cannot be updated when VM is running
```

You could possibly rework the test to replace `lxc launch` by `lxc init`, test `! lxc config set v1 limits.kernel.as... || false`, then `lxc start`.

Or go with a new empty VM that's only ever init'ed, config set failed then deleted.

2024-03-06 23:06 UTC, MggMuggins commented
:facepalm: Had some difficulties getting the tests to run at all and totally missed checking. Fixing...

2024-03-06 23:27 UTC, simondeziel approved these changes
LGTM, thanks! This currently fails because the corresponding lxd PR isn't merged yet but that's fine.

@tomponline that will be backported to 5.0 so no need for version detection/API extension detection logic, right?

2024-03-07 07:56 UTC, tomponline commented
> @tomponline that will be backported to 5.0 so no need for version detection/API extension detection logic, right?

Yeah this seems like something we can backport easily enough.

2024-03-08 15:10 UTC, tomponline requested changes
Please can you rebase your PR so that we only see the final logical commit(s) rather than the evolution of the PR. We don't use squash merges, so we see all PR commit history in the main branch and want it to tell a logical story of changes.

2024-03-08 23:02 UTC, MggMuggins commented
Squashed & passed locally. Good to go so long as the CI agrees.

2024-03-08 23:13 UTC, simondeziel commented
Tests look good: working on `latest/edge` but failing where they should with `5.0/edge` that didn't get the backport yet.

2024-03-09 07:12 UTC, tomponline approved these changes
Thanks!

2024-03-09 07:13 UTC, merged